### ISSUE TITLE
Little question.

### ISSUE THREAD

**Issue by nicholasyoannou** [ReZeroE/AnilistPython#1]
Hi ReZeroE!

First off, thanks for the amazing Anilist wrapper! I'm using this in one of my projects and works amazingly well, so thanks for that. As there's no other way of communicating with you (there's nothing on your GitHub page) I had to resort to opening an issue so sorry about me contacting you through this!

The thing I want to ask is, is there a way to grab AniList links? E.g. going onto an AniList page you have links for Crunchyroll, Funimation, and others. I want to grab those links off AniList but don't see them anywhere in the API wrapper. Is this going to be added in the future?

**Comment by nicholasyoannou** [comment]
Nevermind! Figured out how the code worked, and added it in.

**Comment by ReZeroE** [comment]
Glad to hear! If you have any further questions, feel free to reach out to me over discord (ReZeroK#4910). I'd be happy to offer any help possible.
