### ISSUE TITLE
 Get authenticated user activity

### ISSUE THREAD

**Issue by samuelmarc** [ReZeroE/AnilistPython#13]
I looked in your library for something to get authenticated user activity but I didn't find anything, if possible please add something related to that.

**Comment by ReZeroE** [comment]
Hi there,

Yes, AnilistPython currently does support fetching authenticated users' activity. I'll look into this and let me know if AniList's API supports this.

**Comment by ReZeroE** [comment]
Sounds good. If you make a pull request, I'll merge your changes into the newer version of AnilistPython once I'm ready to release that.
