### ISSUE TITLE
can you please add youtube trailer too?

### ISSUE THREAD

**Issue by noobsohail** [ReZeroE/AnilistPython#7]

**Comment by ReZeroE** [comment]
Sure, I can add a tutorial on youtube sometime during this upcoming summer. If you got any questions, however, feel free to let me know!

**Comment by noobsohail** [comment]
Actually i am talking about "Anime Trailler also get from anilist" can you add that?

**Comment by noobsohail** [comment]
+ Anime Episode Name Search Using "Anime Name - Episode Number" ...

**Comment by ReZeroE** [comment]
I'll look into this. I can add external streaming sites to the library but I need to check to see if their API offers trailer link retrieval. If not, I'll try to work something out and let you know.

**Comment by noobsohail** [comment]
> I'll look into this. I can add external streaming sites to the library but I need to check to see if their API offers trailer link retrieval. If not, I'll try to work something out and let you know.

but anilist provides by default youtube trailer na?

**Comment by ReZeroE** [comment]
I took a look. Their API does offer trailer link retrieval and it'll be either from youtube or dailymotion. According to the GraphQL API:
```
id : String
The trailer video id

site : String
The site the video is hosted by (Currently either youtube or dailymotion)

thumbnail : String
The url for the thumbnail image of the video
```
I'll implement this when I get time. In the meantime, if you want to fork this and make edits to the query string to enable the retrieval of trailer links, feel free to do so. Let me know if you got any questions.

**Comment by janvernieuwe** [comment]
Hi, did you add this? I can't seem to find it anyware and i'm also looking for the youtube trailer link.
