### ISSUE TITLE
Duration

### ISSUE THREAD

**Issue by noobsohail** [ReZeroE/AnilistPython#8]
Can you add video duration too ? That exists in Anilist Api.

**Comment by ReZeroE** [comment]
Will do!

**Comment by noobsohail** [comment]
if possible add (Animes Relations, Like Anime Seasons)

**Comment by ReZeroE** [comment]
Just checked on implementing the following new data section retrievals. 

- Anime Trailer URL
- Anime Studio
- Anime Staff
- Anime Duration (ep average)

Only anime duration can be successfully implemented. Anilist APIv2 doesn't seem to support requests with "trailer", "studio", and "staff" included in the query string. There is nothing I can do on my end to make these work. I'll post an issue under the APIv2 doc and see if their devs can provide me with a solution. 

The following data sections will be added in the upcoming AnilistPython update (ver 0.1.4):
- isAdult
- popularity
- isLicensed
- countryOfOrigin
- duration
- updatedAt
- source
- siteUrl
 
Please let me know if you need any other help.
